/*
 Generated by typeshare 1.10.0-beta.1
*/

export enum Model {
  Gpt35Turbo = 'gpt35-turbo',
  Gpt35Turbo16k = 'gpt35-turbo16k',
  Gpt4 = 'gpt4',
  Gpt432k = 'gpt432k',
  Gpt41106Preview = 'gpt41106-preview',
}

export interface Config {
  store: string;
  openAiApiKey?: string;
  model: Model;
}
