name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  check:
    name: Check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download actionlint
        id: actionlint
        run:
          bash <(curl -s
          https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow
        run: ${{ steps.actionlint.outputs.executable }} -color

  client:
    name: Client

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Info
        run: |
          node --version
          bun --version

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Format
        run: bun run format-check

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun test
